language: python

jobs:
  include:
    - name: "Python 3.7.0 on Xenial Linux"
      python: 3.7
      sudo: required
      install:
        - sudo apt-get install scons libsndio-dev libgtk-3-dev libglu1-mesa libglu1-mesa-dev libgl1-mesa-glx libgl1-mesa-dev libasound2-dev git vim clang-format
        - pip install -r requirements.txt
      script:
        - nuitka3 --follow-imports burn-tool.py --output-dir build --verbose --show-scons --show-progress --standalone
    - name: "Python 3.7.4 on macOS"
      os: osx
      python: 3.7
      osx_image: xcode11.2
      language: shell
      sudo: required
      install:
        - brew install scons
        - pip install --user -r requirements.txt
      script:
        - nuitka3 --follow-imports burn-tool.py --output-dir build --verbose --show-scons --show-progress --standalone

before_install:
  - ls

after_success:
  - ls